### ISSUE TITLE
Unable to discover FFmpeg on Debian

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#1]
To reproduce this issue I've first installed and configured a Debian within VirtualBox:

1. Installed [VirtualBox 5.1 on an Ubuntu 16.04 host](https://help.ubuntu.com/community/VirtualBox/Installation)
1. Installed [Debian 8.8.0](https://cdimage.debian.org/debian-cd/current-live/amd64/bt-hybrid/debian-live-8.8.0-amd64-standard.iso.torrent) in the VirtualBox
1. Inside Debian installed the following packages via `apt-get`:
    * `cmake` (as a side-note: this installs version 3.0.2, but GIFT-Grab has been tested with 3.2)
    * `git`
    * `python-pip`
    * `cmake-curses-gui` (for the `ccmake` command-line interface)
    * `pkg-config` (used by [GIFT-Grab's FFmpeg discovery script](https://github.com/gift-surg/GIFT-Grab/blob/master/src/cmake/ffmpeg/FindFFmpeg.cmake))
1. Inside Debian installed the following [FFmpeg packages](https://wiki.debian.org/ffmpeg#Installation):
    * `libavfilter-dev` (`libavutil-dev`, `libswscale-dev` and `libavcodec-dev` were automatically installed as part of this)
    * `libavformat-dev` (this step creates the missing [`/usr/lib/x86_64-linux-gnu/pkgconfig/libavformat.pc` file](https://people.freedesktop.org/~dbn/pkg-config-guide.html#using))

After the usual `git clone` and build folder creation for GIFT-Grab, calling `cmake -D USE_FILES=ON ../GIFT-Grab/src` fails with the following error:

```
[...]
Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_DIRS FFmpeg_LIBRARY_DIRS)
[...]
```

I've managed to trace this error down to the `pkg-config` ([which is called](https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html) from [GIFT-Grab's FFmpeg discovery script](https://github.com/gift-surg/GIFT-Grab/blob/master/src/cmake/ffmpeg/FindFFmpeg.cmake).
On my Ubuntu 16.04, running `pkg-config --cflags --libs libavformat` gives:

```
-I/home/dzhoshkun/env/giftgrab/usr/local/include -L/home/dzhoshkun/env/giftgrab/usr/local/lib -lavformat
```

Running the same command on Debian 8.8.0 yields only:

```
-lavformat
```

So exactly the `FFmpeg_INCLUDE_DIRS` and `FFmpeg_LIBRARY_DIRS` are missing from the output.

**Comment by stefanv** [comment]
@dzhoshkun I can verify that this is the issue I see.

**Comment by dzhoshkun** [comment]
It turns out that the include and library dirs are not returned by `pkg-config` when a library is installed in a standard location already known to the system. So I will need to relax these in the FFmpeg discovery script.

**Comment by dzhoshkun** [comment]
On the other hand, even after relaxing the include and library dirs in the discovery script, GIFT-Grab does not build against FFmpeg installed via `apt-get install` on Debian (seems to be version 3.2.5, if I read the [version tag](https://packages.debian.org/jessie-backports/ffmpeg) correctly). But I've managed to build it against [FFmpeg version 3.1.2 installed by building from source](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/tips.md#ffmpeg).

@stefanv Which FFmpeg version do you have on your Debian?

**Comment by dzhoshkun** [comment]
Just to be more explicit, these are the two errors I get when running `make`:

```
[...]
GIFT-Grab/src/ffmpeg/ffmpeg_video_source.cpp:381:70 error: 'av_opt_set_int_list' was not declared in this scope
[...]
GIFT-Grab/src/ffmpeg/ffmpeg_video_source.cpp:433:79 error: 'avfilter_graph_parse_ptr' was not declared in this scope
[...]
```

**Comment by dzhoshkun** [comment]
Looks like an API incompatibility between FFmpeg 3.1.2 and 3.2.5. I will investigate this further.

**Comment by stefanv** [comment]
I run Debian testing, which has FFMPEG 3.2.5.

**Comment by dzhoshkun** [comment]
* [ ] **TODO:** document Debian version supported

**Comment by dzhoshkun** [comment]
The two compilation errors documented above do not hold for Debian Testing (see #2)

**Comment by dzhoshkun** [comment]
This issue still holds though. Will relax the include and library dirs requirement now.

**Comment by dzhoshkun** [comment]
@stefanv This issue has been fixed now. I've managed to successfully run the SciPy processing example on Debian testing. Could you please give it a try as well. **Please note:**

* Only the GitHub version has this fix for now, and **not the pip version** (I'll make a new PyPI release once you've confirmed you can run the example)
* GIFT-Grab builds against the Debian-repo FFmpeg version on Debian testing, but **not** on Debian 8.8.0 due to issue #2

**Comment by dzhoshkun** [comment]
@stefanv Have you had time to try the fix? I was thinking, in case it's not clear how to build GIFT-Grab Python bindings from source, i.e. without pip, here is what you need to do:

1. Turn on the following options in CMake:
   * `BUILD_PYTHON`
   * `USE_FILES`
   * `USE_HEVC`
   * `USE_NUMPY`
1. If you're using GPU acceleration, you need to turn on the following options as well:
   * `ENABLE_NONFREE`
   * `USE_NVENC`
1. That is, the whole CMake configuration command looks like: `cmake -D BUILD_PYTHON=ON -D USE_FILES=ON -D USE_HEVC=ON -D USE_NUMPY=ON -D ENABLE_NONFREE=ON -D USE_NVENC=ON ../../GIFT-Grab/src`
1. The subsequent `make` then creates a `pygiftgrab.so` within the build folder, which holds the Python bindings.
1. So the [SciPy example](http://gift-grab.readthedocs.io/en/latest/scipy.html#full-source-code) can be run directly from within the build folder.

In case you have further questions, please let me know.

**Comment by stefanv** [comment]
I now receive the following error:

```
CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_numpy
```

Can you provide a list of packages to install on Debian?

**Comment by dzhoshkun** [comment]
Boost does not support NumPy in versions prior to 1.63. This version is not yet available from the Debian repos, so it needs to be manually installed. To do this, you can follow the steps below:
1. Install NumPy using `apt install python-numpy` (otherwise the Boost build does not install NumPy support)
1. Download [Boost 1.63](http://www.boost.org/users/history/version_1_63_0.html)
1. `./bootstrap.sh --with-libraries=python` (`--with-libraries=python` deactivates all other Boost components, ensuring minimum compilation time)
1. `./b2 install`

**Comment by dzhoshkun** [comment]
I've installed the following packages to make the SciPy example run:

1. `apt install build-essential`
1. One of [NVENC](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/tips.md#nvenc), [kvazaar (default)](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/tips.md#kvazaar) and [x265](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/tips.md#x265) is needed for the encoding. The easiest for me was to use x265, as the Debian FFmpeg seems to support it by default. See [these instructions](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/build.md#hevc) on how to enable one of these encoders in GIFT-Grab.
1. `apt install libavfilter-dev` (this installs all needed FFmpeg components: see the issue description above)
1. `apt install python-dev`
1. `apt install python-numpy`
1. Boost 1.63 as outlined in the above comment
1. `apt install python-scipy`

Then I've built GIFT-Grab using `cmake -D BUILD_PYTHON=ON -D USE_FILES=ON -D USE_HEVC=ON -D USE_NUMPY=ON -D ENABLE_GPL=ON -D USE_X265=ON ../../GIFT-Grab/src`

**Comment by dzhoshkun** [comment]
@stefanv Any luck with this? I was thinking, in case you don't want to disrupt your system-wide Boost installation when installing 1.63; you can install it locally and [use `BOOST_ROOT` to let GIFT-Grab pick up the correct one](http://www.boost.org/doc/libs/1_63_0/more/getting_started/unix-variants.html#the-boost-distribution)

**Comment by stefanv** [comment]
Had to: `export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python3.5/"` to get Boost to build

**Comment by stefanv** [comment]
BOOST_ROOT does not seem to work

**Comment by stefanv** [comment]
@dzhoshkun Could you please verify whether you can use boost without installing it system wide?

**Comment by dzhoshkun** [comment]
@stefanv Yes, I can. I've used it for a very long time on our test server (Ubuntu). I've now also reproduced it on Debian Testing.

**Comment by dzhoshkun** [comment]
@stefanv `BOOST_ROOT` must be the include directory containing a `boost` folder.

On my system I built Boost using:
```
./bootstrap.sh --with-libraries=python --prefix=/home/dzhoshkun/tools
./b2 install
```

This creates `/home/dzhoshkun/tools/include/boost` where the Boost headers are located.
I then did a `export BOOST_ROOT=/home/dzhoshkun/tools/include` before `cmake`ing GIFT-Grab, and that works.

**Comment by stefanv** [comment]
Further notes:

- CPLUS_INCLUDE_PATH is necessary, otherwise pyconfig.h not found
- `b2 install` copies headers, even if build fails, but install may be broken; so perhaps `./b2; ./b2 install` is to be recommended?
- You need to specify `-D BOOST_ROOT=...`, *NOT* with a shell export (perhaps a caching issue)

I'm now running into:

```
CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.63.0

  Boost include path: /home/stefan/src/boost_install/include

  Could not find the following Boost libraries:

          boost_numpy

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  cmake/boost.python/CMakeLists.txt:7 (FIND_PACKAGE)
```

**Comment by stefanv** [comment]
I also see:

```
$ find ~/src/boost_install/include/boost/* -iname "*numpy*"
/home/stefan/src/boost_install/include/boost/python/numpy.hpp
/home/stefan/src/boost_install/include/boost/python/numpy
/home/stefan/src/boost_install/include/boost/python/numpy/numpy_object_mgr_traits.hpp
```

and 

```
$ find ~/src/boost_install/lib/* -iname "*numpy*"
/home/stefan/src/boost_install/lib/libboost_numpy3.a
/home/stefan/src/boost_install/lib/libboost_numpy3.so
/home/stefan/src/boost_install/lib/libboost_numpy3.so.1.63.0
/home/stefan/src/boost_install/lib/libboost_numpy.a
/home/stefan/src/boost_install/lib/libboost_numpy.so
/home/stefan/src/boost_install/lib/libboost_numpy.so.1.63.0
```

Could this detection problem be in GIFT-Grab?

**Comment by dzhoshkun** [comment]
re `CPLUS_INCLUDE_PATH`: I've never had to use this. Neither on our test server (Ubuntu), nor on my Debian. But will:

* [x] add it to the caveats

**Comment by dzhoshkun** [comment]
re `./b2; ./b2 install`: Agreed. I will:
* [x] change the Boost build instructions (just to be clear: this is not a GIFT-Grab issue, but good to have it in the instructions we provide)

**Comment by dzhoshkun** [comment]
re `-D BOOST_ROOT=...`: for me `BOOST_ROOT` as a shell variable works (both on Ubuntu and Debian). Probably a CMake caching issue then.

**Comment by dzhoshkun** [comment]
re `boost_numpy` not found:

It's not a GIFT-Grab problem. GIFT-Grab [just calls `FIND_PACKAGE(Boost ...)`](https://github.com/gift-surg/GIFT-Grab/blob/master/src/cmake/boost.python/CMakeLists.txt#L7)

See my comment above starting with "Boost does not support NumPy". The absence of NumPy on the system **when building Boost** is the only problem I've come across so far related to being unable to discover `boost_numpy`. But on your system everything seems to be there.

This might be related to the "re `-D BOOST_ROOT=...`" issue (my previous comment). I'd recommend starting a fresh CMake (= deleting everything in the CMake folder); CMake sometimes caches things in an inconvenient way and fails to discover updated settings.

**Comment by stefanv** [comment]
Success!  It was the `CMakeCache.txt` and `CMakeFiles`

**Comment by stefanv** [comment]
I think we're close.

```
$ LD_LIBRARY_PATH=~/src/boost_install/lib/ python -c "import pygiftgrab"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/stefan/src/GIFT-Grab/pygiftgrab.so: undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE
```

**Comment by dzhoshkun** [comment]
That looks like a Python version problem. Can you please verify that:
* you are using Python 2
* your Boost is built and linked against Python 2 libs

**Comment by stefanv** [comment]
Python 3 is not supported?

**Comment by dzhoshkun** [comment]
No, not yet.

**Comment by stefanv** [comment]
If you can incorporate everything we've learned above into the installation instructions, I think we're good to go.  The installation document may be quite overwhelming, so it would be good to have clear, step-by-step installations for building a minimal version (much like you had me do above).

**Comment by stefanv** [comment]
Also, it'd be good to mention the Python 3 issue very prominently, if it is not already stated so.

**Comment by dzhoshkun** [comment]
* [x] **re "incorporate everything we've learned"**

Sure. Could you please let me know your system specs such as [these](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/requirements.md#operating-system)

* [x] **re "Python 3 issue"**

There is already a detailed [list of the supported versions of all dependencies](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/requirements.md#optional-dependencies). But I've noticed now that it's a bit obscured by the way the documentation is structured. I'm going to revise the documentation to give it more visibility.

**Comment by stefanv** [comment]
Great, thank you!

My system info:

```
Debian 9 (testing), Linux 4.9.0-2-amd64
gcc 6.3.0
ffmpeg 3.2.4
cmake 3.7.2
Python 3.6.0 <-- the problem ;)
boost 1.63
```

**Comment by stefanv** [comment]
@dzhoshkun Let me know when you are ready for us to wrap this up.

**Comment by dzhoshkun** [comment]
@stefanv Sure. I'm restructuring the documentation, as your feedback made me realise that it's not that easy for the user to find the relevant information and instructions due to the way it's structured. I'm also polishing the GIFT-Grab PyPI page: PyPI has recently been migrated to a new platform with an improved web interface, and the current GIFT-Grab PyPI page doesn't look very appealing on the new PyPI.

Once these tasks are finished (should be very soon now), I'm going to publish a new release on PyPI and let you know.

**Comment by dzhoshkun** [comment]
@stefanv I've incorporated everything we've learned into the documentation now. I've also restructured and revised the documentation to make it easier for the user to find information.

In particular:
* Restructured the main README file to reduce content and to make it easier for the user to find relevant information.
* Added instructions for building a minimal GIFT-Grab version for testing NumPy compatibility: https://github.com/gift-surg/GIFT-Grab/blob/master/doc/minimal.md
* Made the requirements and the dependency installation guidelines sections more visible and easier to find.
* Emphasised the need for pip install options for installing GIFT-Grab from PyPI.
* Revised the GIFT-Grab PyPI description to make the GIFT-Grab PyPI page a bit more appealing and more useful to the user.
* Known issues and limitations are now kept in a separate MD file: https://github.com/gift-surg/GIFT-Grab/blob/master/doc/issues.md
* More internal cross-links to make it easier for the user to browse and navigate the documentation.

(For more details, please see the CHANGELOG)

I've published a 1708 release candidate on PyPI: https://pypi.org/project/GIFT-Grab/1708rc4/

I've been able to install this RC successfully on my Debian Testing and subsequently to run the SciPy example with it.
Would you be able to give it a try on your Debian as well, using this command:

```
pip install gift-grab==1708rc4 --install-option="--files" --install-option="--hevc" --install-option="--x265" --install-option="--enable-gpl" --install-option="--numpy"
```

**`==1708rc4` is important as otherwise pip will just pick the last stable release from May**

Once you've confirmed this RC installs successfully on your system, I will:
* [x] publish the official 1708 release as well

**Comment by stefanv** [comment]
This all looks great---and it works!  Consider:

- Linking to the minimal build document from the README
- Mentioning that the project only builds on Python 2
- Mentioning BOOST_ROOT for alternative installation path.

**Comment by dzhoshkun** [comment]
Awesome!

* re "Linking to the minimal build document from the README": there already is a link in the Getting started section
* re "Mentioning that the project only builds on Pytho2": was already mentioned in the project summary in README, but also added explicit note in the minimal example
* re "Mentioning BOOST_ROOT for alternative installation path.": agreed, and added a note to the minimal example.
