### ISSUE TITLE
Use CMake property for setting C++11 standard

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#106]
[`CXX_STANDARD`](https://cmake.org/cmake/help/v3.14/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) in conj. with [`CXX_STANDARD_REQUIRED`](https://cmake.org/cmake/help/v3.14/prop_tgt/CXX_STANDARD_REQUIRED.html#prop_tgt:CXX_STANDARD_REQUIRED) for enforcing it should be used rather than the current configuration, which merely sets the compiler flag, and may hence impede cross-platform compatibility.

**Comment by dzhoshkun** [comment]
* [ ] using CMake properties for setting C++ standard does not seem to work under Linux, see https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/205563082, hence the above commit, which might need to be checked later on

**Comment by joubs** [comment]
Closing as out of date.
