### ISSUE TITLE
Boost.Python version 3 (compiled from source) discovery needs minor version for on Linux as well

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#113]
When building Boost.Python libraries from source, the following files are installed:

* `/home/dzhoshkun/ws/_i/boost/lib/libboost_numpy37.so`, which points to `/home/dzhoshkun/ws/_i/boost/lib/libboost_numpy37.so.1.69.0`
* `/home/dzhoshkun/ws/_i/boost/lib/libboost_python37.so`, which points to `/home/dzhoshkun/ws/_i/boost/lib/libboost_python37.so.1.69.0`

However when installing Boost.Python libraries via `apt install`, 

* `/usr/lib/x86_64-linux-gnu/libboost_numpy3.so`, which points to `/usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so`
* `/usr/lib/x86_64-linux-gnu/libboost_python3.so`, which points to `/usr/lib/x86_64-linux-gnu/libboost_python3-py36.so`

**Comment by joubs** [comment]
Closing as out of date.
