### ISSUE TITLE
Edit to tips for BlackMagic cards

### ISSUE THREAD

**Issue by cbergeles** [gift-surg/GIFT-Grab#117]
I suggest that a new step is added at the end of /master/doc/tips.md, section Blackmagic Drivers and Blackmagic Desktop Video SDK. 

The ReadMe.txt within Blackmagic_Desktop_Video_Linux contains a troubleshooting section on how to make sure the drivers are properly installed. In a couple of cases for me the drivers did not install the first time.

**Comment by dzhoshkun** [comment]
During our debugging session today, we ran into "boost error already set" errors, as the BM card was not properly configured to acquire stereo video.
When we subsequently ran Media Express and set the input format correctly, visually making sure it captured stereo video properly, the same GG script suddenly started working.

So, in the documentation it'd be good to also include a note about using Media Express as a first checkpoint.

**Comment by joubs** [comment]
Closing as out of date.
