### ISSUE TITLE
Error when using PIP to install

### ISSUE THREAD

**Issue by melloajello** [gift-surg/GIFT-Grab#12]
I get the following error when trying to install GIFT-grab from PIP:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\najello\appdata\local\temp\pip-install-ahxgri\gift-grab\setup.py", line 7, in <module>
        from os import mkdir, chdir, listdir, getcwd, link, rename
    ImportError: cannot import name link 
```
As far as I know "os" has no module name "link".  Is this the issue or is it on my end?

**Comment by dzhoshkun** [comment]
@melloajello Thank you for reporting this.

[`os.link` seems to be available](https://docs.python.org/2/library/os.html#os.link).

You seem to be using Windows. Please note GIFT-Grab hasn't been tested on Windows yet. But I'd love to support Windows as well. Could you please provide the following details of your platform:
* Windows version
* Python version
* The command you are running to install GIFT-Grab

**Comment by dzhoshkun** [comment]
@melloajello As I haven't heard back from you for a long time, I'm closing this issue. If you're still interested in pursuing it, please feel free to reopen.
