### ISSUE TITLE
Output to DeckLink SDI

### ISSUE THREAD

**Issue by bobmilani** [gift-surg/GIFT-Grab#13]
I am not sure if I over looked the API page but I didn't see anyway to output to the VideoCapture Device.

Can you tell me which API call it is or a sample?

If not would be a good enhancement.

Thanks
Bob

**Comment by dzhoshkun** [comment]
@bobmilani Thanks for this. Do I understand correctly that you would like to output data processed with GIFT-Grab back on to an output port of a DeckLink device?

**Comment by bobmilani** [comment]
Yes, that is correct.

**Comment by dzhoshkun** [comment]
I'm afraid GIFT-Grab does not support this functionality yet. It'd indeed be a nice feature to have.

**Comment by joubs** [comment]
Closing as out of date.
