### ISSUE TITLE
Untested removal of "user" device-specific tests installed via pip

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#26]
As part of #24 the pip-installed "user" tests are going to be removed from the CI script and replaced with the corresponding `pytest` calls.
These should be harmless, i.e. should not jeopardise functionality.
The worst that can happen is that CI script will break.
Nonetheless, we should run the device-specific CI scripts to preclude any regressions.

**Comment by joubs** [comment]
Closing as out of date.
