### ISSUE TITLE
Add streaming capabilities to create a rtsp stream from within GIFT-Grab

### ISSUE THREAD

**Issue by tvercaut** [gift-surg/GIFT-Grab#3]
As discussed earlier with @MattClarkson and @luiscarlosgph it would be nice to be able to create a video stream from within GIFT-Grab. There is already support for receiving a video stream thanks to libvlc. Something similar could be done to stream out from GIFT-Grab.

For the record, here are a few somewhat random pointers I have been looking into to see how difficult it is to use libvlc to stream out. It looks like some of the key functions would be:
```
sprintf(arg[0], "--imem-get=%ld", myImemGetCallback);
sprintf(arg[1], "--imem-release=%ld", myImemReleaseCallback);

libvlc_vlm_add_broadcast(...)
```

https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__vlm.html#gaa8d58569f07229edabe9fdaab41b1c3d
https://github.com/leixiaohua1020/simplest_libvlc_example/blob/master/simplest_libvlc_streamer/simplest_libvlc_streamer.cpp
https://forum.videolan.org/viewtopic.php?t=89408
https://stackoverflow.com/questions/47439099/how-to-broadcast-video-from-imem-in-libvlc
https://forum.videolan.org/viewtopic.php?t=93842
https://github.com/john-tornblom/vlc-omem/blob/master/test.c

**Comment by tvercaut** [comment]
As discussed briefly with @dzhoshkun, it would be neat to test streaming out from GIFT-Grab on a small windows PC. This would ease working with the [NanEye sensor](http://www.cmosis.com/products/product_detail/naneye_module) and corresponding [USB3 kit](http://www.cmosis.com/products/product_detail/naneye_usb3_demo_kit).

It looks like we could have a small raspberry pi like solution but with windows IoT and a USB 3 powered minnowboard:
https://blogs.windows.com/buildingapps/2015/08/10/hello-windows-10-iot-core/#XMI18cfIJjKfpHKX.97
https://developer.microsoft.com/en-us/windows/iot
https://minnowboard.org/minnowboard-turbot/technical-specs

**Comment by MattClarkson** [comment]
im not familiar with these things. what's the objective? I have a raspberry pi, a camera, and also a jetson TK1 if that helps?

**Comment by dzhoshkun** [comment]
Possibly a `VideoTargetFactory::create_network_streamer` along the lines of [`VideoTargetFactory::create_file_writer`](https://codedocs.xyz/gift-surg/GIFT-Grab/classgg_1_1_video_target_factory.html#adacfc7db06b4a0fa924b269a9a22af08)

The network stream capturing is currently done via [`VideoSourceFactory::connect_network_source`](https://codedocs.xyz/gift-surg/GIFT-Grab/classgg_1_1_video_source_factory.html#a0d39bea6386593ac962e268b7325ce92)

**Comment by dzhoshkun** [comment]
[RTSP specification](https://tools.ietf.org/html/rfc2326) says:

> Besides the media parameters, the network destination address and
>   port need to be determined. Several modes of operation can be
>   distinguished:

>   Unicast:
>          The media is transmitted to the source of the RTSP request,
>          with the port number chosen by the client. Alternatively, the
>          media is transmitted on the same reliable stream as RTSP.

>   Multicast, server chooses address:
>          The media server picks the multicast address and port. This is
>          the typical case for a live or near-media-on-demand
>          transmission.

>   Multicast, client chooses address:
>          If the server is to participate in an existing multicast
>          conference, the multicast address, port and encryption key are
>          given by the conference description, established by means
>          outside the scope of this specification.

**Comment by dzhoshkun** [comment]
[FFmpeg supports streaming as well](https://trac.ffmpeg.org/wiki/StreamingGuide), and here's a [C++ example](https://github.com/leixiaohua1020/simplest_ffmpeg_streamer/blob/master/simplest_ffmpeg_streamer/simplest_ffmpeg_streamer.cpp)

**Comment by MattClarkson** [comment]
Where do we sit with ffmpeg which in itself is LGPL up until the point at which you compile in some GPL codec such as x264 whereupon all code is deemed to be GPL, including anything that uses ffmpeg.

**Comment by dzhoshkun** [comment]
@MattClarkson How do you mean?

[GIFT-Grab already uses FFmpeg, with the corresponding options upgrading GIFT-Grab to GPL, if switched on](https://github.com/gift-surg/GIFT-Grab/blob/master/doc/build.md#hevc)

**Comment by MattClarkson** [comment]
Fine. At least its documented.

**Comment by dzhoshkun** [comment]
* [ ] test options:
   1. [ ] [FFmpeg CLI](https://trac.ffmpeg.org/wiki/StreamingGuide):
       - `ffmpeg -i input -f rtsp -rtsp_transport tcp rtsp://localhost:8888/live.sdp` (send)
       - `ffplay -rtsp_flags listen rtsp://localhost:8888/live.sdp?tcp` (receive)
   1. [ ] [standard Python `socket`](https://github.com/golubaca/python-streaming-server/blob/master/client/recv.py)
   1. [ ] VLC CLI

**Comment by dzhoshkun** [comment]
The feature branch will be hosted [on CMICLab](https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/234).

**Comment by dzhoshkun** [comment]
* [ ] New build options for CMake and pip

**Comment by dzhoshkun** [comment]
* [ ] pypi test job for network streaming

**Comment by dzhoshkun** [comment]
* [ ] does the use of FFmpeg for network streaming imply `ENABLE_NONFREE` or GPL (and the corresponding pip install option) ?

**Comment by dzhoshkun** [comment]
* [ ] in tests possibly rename `network` folder => `network-sources` to avoid confusion **OR** into a `network/source` and `network/target` hierarchy

**Comment by dzhoshkun** [comment]
* [ ] document new CMake option
* [ ] document new PyPI option

**Comment by dzhoshkun** [comment]
* [ ] link `USE_NETWORK_TARGETS` to the relevant dependency in main CMake file

**Comment by joubs** [comment]
Closing as out of date.
