### ISSUE TITLE
Consider adding the multi-threading reliability checker to CI

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#36]
As of #16, a multi-threading reliability checker script running a relatively complex processing pipeline and checking the exit codes for segfaults is added to the codebase.
It might be a good idea to include this in the CI script as well.
However that will require test videos, and a bit configuration, so documenting it as a potential action item for later.
See #33

**Comment by joubs** [comment]
Closing as out of date.
