### ISSUE TITLE
Support for VideoFrame flag indicating whether the data has been processed

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#37]
This idea came up during the discussion with @cbergeles and his team on 23 Oct 2018.
Sometimes in video processing pipelines it's important for a processing node to know whether the previous node has processed the video frame it has passed to that node.
So it might be a good idea to add a flag to `VideoFrame` indicating whether it has been processed.

On the other hand, relying solely on this information in a real-time, multi-threaded application might lead to problems when a shared `VideoFrame` is passed from node to node.
This warrants a mechanism such as a mutex to ensure thread-safe access to the flag.

A better approach might be to use a counter as a flag, i.e. indicating how many nodes a video frame has been processed by.
This is such that e.g. node `k` can ensure the video frame has been processed by `k-1` nodes before doing its job.

**Comment by joubs** [comment]
Closing as out of date.
