### ISSUE TITLE
Support for dropping frames

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#38]
Again an idea that came up during the discussion with @cbergeles and his team on 23 Oct 2018.
In real-time video processing pipelines, not all nodes can process a video frame at the same rate.
Some will be faster while others are slower.
In the current architecture, video frames are continuously propagated from node to node.
This effectively means that slower nodes are by-passed.

However often a node's processing method relies on another node's output, which in a by-passing scenario gets lost.
It might be a good idea to add support for dropping frames, e.g. node A processes a frame every 100 msec, and propagates **that particular frame** down the pipeline, essentially dropping all others.

**Comment by cbergeles** [comment]
@dzhoshkun I'm confused about the statement "This effectively means that slower nodes are by-passed". I though that if a frame is not processed, then a lag is built up. Can you clarify?

**Comment by dzhoshkun** [comment]
@cbergeles I meant that if a processing node chooses to drop frames while processing another, essentially the frame it's currently processing will never be passed to the subsequent nodes. E.g. the following case:

```python
def update(frame):
    """Implement IObserver.update."""
    if self.processing:
        pass
    else:
        self.processing = True
        process_in_separate_thread(frame)  # self.processing flag will be reset when thread finishes
```

However in the following case a lag will build up, as you've pointed out:

```python
def update(frame):
    """Implement IObserver.update."""
    process_in_this_thread(frame)
```

**Comment by cbergeles** [comment]
Gotcha. I think the combination of this and frame dropping is critical.

**Comment by tvercaut** [comment]
A couple of comments from my side.

1. Rather than having frame dropping be explicitly handled by the node's update method, this should be factorised in the parent to avoid code duplication and ensuring a robust implementation.

2. How do you handle parallel processing with this model? It might be that a node could handle real-time processing by spawning 2 threads. For another project, we provided a thread pool to each node and only started dropping frames when the entire thread pool was busy rather than dropping as soon the the more is busy. This might provide more flexibility already but better architectures can probably be thought of.

**Comment by tvercaut** [comment]
The other perk we ended up having for each node was a buffer holding past unprocessed frames, i.e. having a queue. The maximum number of frames was capped to avoid blowing up the memory but the queuing process allowed us to avoid dropping too many frames in case where the average processing time is compatible with real-time but the peaks are not.

**Comment by tvercaut** [comment]
One further design consideration that might be worth keeping is that of post-processing. In cases where the input is a file and not a real-time stream, it may be important to apply the processing to each and every frame without frame drop and using all the computational capacity. Essentially requesting frames to the reader as soon as the node is free rather than handling frames pushed by the frame grabber.

**Comment by cbergeles** [comment]
I'm just worried that adding full blown video play capabilities will align it more to an opencv video reader, and therefore distracting from the primary goal. On the otherhand, if it is has the semi-hard constraint of always pushing images, people will use it only when they have something almost real-time at hand.

**Comment by dzhoshkun** [comment]
Re: 
> post-processing. In cases where the input is a file and not a real-time stream

I agree this is a valid use case esp. considering we've open-sourced GIFT-Grab for use by the research community. I know for instance Loic was using GIFT-Grab in this manner with a custom patch I provided him. I will

* [ ] file a new issue for this.

For real-time streams from external devices captured via frame-grabbers, GIFT-Grab's relevant classes capture frames in very device-specific ways to preclude duplicates. Some SDKs provide callback mechanisms to notify clients when a new frame is available (e.g. Blackmagic), while others operate on a polling basis (e.g. Epiphan). The former case is trivial. In the latter one, GIFT-Grab uses device-specific information to poll the relevant device at time intervals in line with that device's specified (and measured) frame rate (see the discussion on `BroadcastDaemon` in the [GIFT-Grab paper](http://doi.org/10.5334/jors.169)). However as a design decision this is transparent to the user by virtue of an API that uses the abstract factory design pattern.

So I'd rather keep the device interface as is, but provide a flexible frame-dropping mechanism instead.

**Comment by tvercaut** [comment]
An example use case if you have some processing that can run faster than real-time (say geometric distortion compensation) and you want to apply it as post-processing on a batch of video files. If for real-time application you already have a GIFT-Grab based pipeline, it is really nice to be able not to need another tool for the post-processing application.

I am wondering whether this could be achieved by having the `BroadcastDaemon` "listen" to the last node and only query the file reader when the last node is idle.

Additionally, if you can configure your processing nodes with a configuration file to enable or disable frame drop / frame queuing / parallel processing / etc that could help support several use cases without modifying the code base.

**Comment by dzhoshkun** [comment]
Re:

> Rather than having frame dropping be explicitly handled by the node's update method, this should be factorised in the parent to avoid code duplication and ensuring a robust implementation.

Maybe we should make a distinction between Python and C++ at this point. In Python the current architecture represents a processing node by the `IObservableObserver` interface, which however was introduced as a workaround to a Python multiple inheritance problem (#47). In C++ this problem does not exist so a processing node is one that implements both `IObservable` and `IObserver`.

Although I see the point of handling frame-dropping in the parent with regards to robustness and code duplication, I'm not sure how much room that will leave for flexibility in Python-based use cases where most of the application logic will reside at Python level. Maybe flexibility can be achieved by a generic "stopping" buffer node to be inserted before slow processing nodes, such that this "stopping" buffer:
1. is aware of the processing node's current status, and
1. does not `update` the processing node until the processing node has finished processing the current frame
1. and can be configured to either drop frames or buffer a number of them until the processing node is free

**Comment by dzhoshkun** [comment]
After my discussion with @tvercaut the "stopping" buffer idea sounds less suitable for real-time processing, esp. considering the potential (and actually probable!) need for multi-threading. Instead we've agreed that it'd be a good idea to handle frame-dropping in conj. with thread-pooling at C++ level, e.g. allowing the user to set the max no of threads per processing node. In this manner the multi-threading is handled semi-transparently to the user, allowing them to focus on implementing their custom method without having to deal with the low-level technicalities of multi-threading. This is more or less an expansion of idea no 2. in https://github.com/gift-surg/GIFT-Grab/issues/38#issuecomment-433964338.

**Comment by joubs** [comment]
Closing as out of date.
