### ISSUE TITLE
Stereo image de-interlacing clarity

### ISSUE THREAD

**Issue by RViMLab** [gift-surg/GIFT-Grab#4]
It is a bit unclear yet how Gift grab can be used in the context of stereo image capture (de-interlacing?).

**Comment by dzhoshkun** [comment]
@RViMLab @cbergeles Is this the same as #5 ? If not, could you please clarify.

**Comment by cbergeles** [comment]
@dzhoshkun Indeed, this should be the same.

**Comment by dzhoshkun** [comment]
Thanks @cbergeles 

Closing this issue in favour of #5 then.
