### ISSUE TITLE
Support for cross-Python testing

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#42]
Currently the CI script uses the platform-default Python for running the tests.
It'd be great to be able to test for both Python 2 and 3 with the least amount of duplicate configuration.
We should be able to minimise the duplication using tox.
However we should also bear in mind that each Python version will require Boost to have been built against that particular Python version.

**Comment by dzhoshkun** [comment]
* [ ] not using `exit_on_fail` ? (above commit)

**Comment by dzhoshkun** [comment]
* [x] is the above commit a good idea?

**Comment by dzhoshkun** [comment]
* [ ] next: pip installer tests via tox

**Comment by dzhoshkun** [comment]
* [x] last tests py27 failed?

**Comment by dzhoshkun** [comment]
* [x] **REVERT ABOVE COMMIT**

**Comment by dzhoshkun** [comment]
On Kyrie:

```bash
[0] % ldd /home/dzhoshkun/ws/giftgrab-scratch/3aea2d0/build/py35/libgiftgrab.so
	...
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f73e0a22000)
```

**Comment by dzhoshkun** [comment]
* [ ] the above commit should be reverted: pip installer failure check

**Comment by joubs** [comment]
Closing as out of date.
