### ISSUE TITLE
Add compiler optimisation flags to CMake configuration

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#45]
It looks like [compiler optimisation flags can make a huge difference](https://stackoverflow.com/q/25576413). We should consider enforcing these in the CMake configuration, if not already default. However it'll probably be a good idea to run the whole CI test suite after making changes related to this, and possibly a real-time video processing pipeline.

**Comment by joubs** [comment]
Closing as out of date.
