### ISSUE TITLE
Python MRO problems with intermediate pipeline nodes

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#47]
From [original issue](https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/166):

A pipeline node needs to inherit from both `IObserver` and `IObservable`. However this causes [MRO](https://www.python.org/download/releases/2.3/mro/) problems: namely the extending class gets resolved to either type, not both, at runtime.

We need to investigate whether this issue is still valid. If not, it could be a good idea to support multiple inheritance from both `IObserver` and `IObservable` in Python and deprecate `IObservableObserver`, which was introduced as a workaround to this problem.

**Comment by joubs** [comment]
Closing as out of date.
