### ISSUE TITLE
Support for 3D capture on BlackMagic cards

### ISSUE THREAD

**Issue by cbergeles** [gift-surg/GIFT-Grab#5]
It seems that in order to capture 3D, one needs on top of the first “mode” check, to do a check for a flag “bmdDisplayModeSupports3D flag in the return value of IDeckLinkDisplayMode::GetFlag. I looked into gift-grab and it is mentioned that the blackmagic part is based on Luis contribution. I think that the check should be in blackmagicksdk_video_source.cpp, at the end: "BMDDisplayMode display_mode_ = detector.get_display_mode();”

Should I check with Luis, or do you have any ideas on this @dzhoshkun? I’ll try to edit the code and compile but yeah, either of you would probably be faster ;)

**EDIT (13 Nov 2018)** (these are action items for @dzhoshkun, which will get obscured in the thread below after the imminent massive rebase onto the master branch): 

* [x] revert e404a05, ee70ecc, e404a05
* [x] 61968a3 **SHOULD NOT BE MERGED** into master
* [x] when this issue is resolved, consider documenting the 3D test script, e.g. in RTD
* [x] Had to install [additional components](https://askubuntu.com/a/471501) on trinidad.
* [ ] https://github.com/gift-surg/GIFT-Grab/issues/14#issuecomment-411794218
* [x] update BM-related installation hints, BM drivers are now part of [`Blackmagic_Desktop_Video_Linux_10.11.1.tar` rather than the SDK](https://github.com/gift-surg/docs/wiki/GiftKyrie#blackmagic-video-sdk) package (as of 10.4)

```bash
sudo dpkg -i desktopvideo_10.11.1a4_amd64.deb
BlackmagicFirmwareUpdater
BlackmagicFirmwareUpdater status
BlackmagicFirmwareUpdater update
BlackmagicFirmwareUpdater update 0
sudo dpkg -i desktopvideo-gui_10.11.1a4_amd64.deb
sudo dpkg -i mediaexpress_3.5.6a2_amd64.deb
```

* [x] one-liner `/etc/ld.so.conf.d/blackmagic-sdk.conf` to allow for [missing `libc++1.so.1`](https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/86369059) to be discovered

**Comment by tvercaut** [comment]
Adding @luiscarlosgph in the discussion

**Comment by dzhoshkun** [comment]
The `Linux/Samples/Capture/Capture.cpp` example of the SDK (version 10.11.1) shows how to enable 3D capture using two sources. In particular,

1. [x] the [display mode detector](https://github.com/gift-surg/GIFT-Grab/blob/87a0e922cb8174b6648fbfdb82849d4ffc9569b9/src/blackmagicsdk/deck_link_display_mode_detector.cpp#L63) should call `EnableVideoInput` using the `bmdVideoInputDualStream3D` flag to query this
1. [x] the [actual video source](https://github.com/gift-surg/GIFT-Grab/blob/87a0e922cb8174b6648fbfdb82849d4ffc9569b9/src/blackmagicsdk/blackmagicsdk_video_source.cpp#L94) should then also use this flag when calling `EnableVideoInput`

**Comment by dzhoshkun** [comment]
* [x] This issue depends on #7, as the changes will need to be tested using a BM card

**Comment by dzhoshkun** [comment]
* [ ] update BM-related installation hints, BM drivers are now part of [`Blackmagic_Desktop_Video_Linux_10.11.1.tar` rather than the SDK](https://github.com/gift-surg/docs/wiki/GiftKyrie#blackmagic-video-sdk) package (as of 10.4)

```bash
sudo dpkg -i desktopvideo_10.11.1a4_amd64.deb
BlackmagicFirmwareUpdater
BlackmagicFirmwareUpdater status
BlackmagicFirmwareUpdater update
BlackmagicFirmwareUpdater update 0
sudo dpkg -i desktopvideo-gui_10.11.1a4_amd64.deb
sudo dpkg -i mediaexpress_3.5.6a2_amd64.deb
```

* [ ] one-liner `/etc/ld.so.conf.d/blackmagic-sdk.conf` to allow for [missing `libc++1.so.1`](https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/86369059) to be discovered

**Comment by dzhoshkun** [comment]
* [x] set up BM converter+source on Kyrie for CI tests, and retry above failed build

**Comment by dzhoshkun** [comment]
* [ ] https://github.com/gift-surg/GIFT-Grab/issues/14#issuecomment-411794218

**Comment by dzhoshkun** [comment]
* [ ] Had to install [additional components](https://askubuntu.com/a/471501) on trinidad.

**Comment by dzhoshkun** [comment]
* [x] trinidad now complains there's no BM card installed on the system. A closer inspection reveals `desktopvideo 10.9.10a2: blackmagic-io kernel module failed to build` (this has happened after updating the system software via the Ubuntu software updater, and restarting the machine)

**Comment by dzhoshkun** [comment]
Managed to resolve the above problem by installing the new version of the driver (11.9). In particular:

```bash
sudo dpkg -i desktopvideo_*.deb
sudo dpkg -i desktopvideo-gui_*.deb mediaexpress_*.deb
sudo apt-get install -f
```

(see the `ReadMe.txt` file provided as part of the `Blackmagic_Desktop_Video_Linux_10.11.2.tar` archive)

**Comment by dzhoshkun** [comment]
Running the `/opt/Blackmagic_DeckLink_SDK_10.11.2/Linux/Samples/Capture` application as part of the GIFT-Grab codebase using `./tests/blackmagic/decklinksdi4k/Capture -d 0 -m 10 -3 -v video3d.raw -n 50` seems to work. I.e. it produces the output file, but it remains to:

* [x] verify the nature of the saved frames, i.e. are they 3D? (e.g. by covering one "eye" of the attached camera system, and saving a number of frames to be inspected)

In any case, the above committed changes were made on the basis of the sample capture application, whose checking/setting of the `bmdVideoInputDualStream3D` flag seems to work. So:

* [x] we should verify them against the capture application logic

**Comment by dzhoshkun** [comment]
Turns out that the `bmdVideoInputEnableFormatDetection` and the `bmdVideoInputFlagDefault` flags are mutually exclusive in the case where stereo is involved, i.e. the `bmdVideoInputDualStream3D` flag is used.

**Comment by dzhoshkun** [comment]
* [x] run the CI pipeline with the above commit

**Comment by dzhoshkun** [comment]
Some of the tests that fail above (on Kyrie), seem to succed on Trinidad. On Trinidad we don't get the `VideoSourceError: Could not check video mode support of Blackmagic DeckLink device` error.

**Comment by dzhoshkun** [comment]
* [x] do verify (https://github.com/gift-surg/GIFT-Grab/issues/5#issuecomment-425448721) frames saved using GG as well

**Comment by dzhoshkun** [comment]
It looks like input from only one of the stereo cameras is captured.

**Comment by dzhoshkun** [comment]
* [ ] when this issue is resolved, consider documenting the 3D test script, e.g. in RTD

**Comment by dzhoshkun** [comment]
* [x] need to call `GetFrameForRightEye` (see the Capture example of BM SDK)
* [x] as a test, try to return the "right-eye" frame from within the BM video source instead of the default one, and see if it corresponds to the second camera

**Comment by dzhoshkun** [comment]
* [ ] possibly need to extend `VideoFrame` e.g. add a `stereo` or `3D` flag such that the data from the stereo frame can be stored in a separate buffer

**Comment by dzhoshkun** [comment]
Possibly smt like:
- `has_stereo()`
- `data(bool stereo = false)`: returning the "right-eye" frame

**Comment by dzhoshkun** [comment]
* [ ] 61968a3 **SHOULD NOT BE MERGED** into master

**Comment by dzhoshkun** [comment]
As of the above commit, GIFT-Grab can capture stereo frames from a DeckLink 4K Extreme 12G. However this is a hack for the time being (https://github.com/gift-surg/GIFT-Grab/issues/5#issuecomment-429725468). Need to extend the API (https://github.com/gift-surg/GIFT-Grab/issues/5#issuecomment-429349429) to properly support this feature.

Will:
* [ ] write tests first

**Comment by dzhoshkun** [comment]
Potentially useful design patterns:
* [Decorator](https://sourcemaking.com/design_patterns/decorator)
* [Composite](https://sourcemaking.com/design_patterns/composite)
* [Private Class Data](https://sourcemaking.com/design_patterns/private_class_data)

* [ ] have a deeper look into these (and possibly others)

**Comment by cbergeles** [comment]
This is fantastic Dzhosh!

**Comment by dzhoshkun** [comment]
* [ ] revert e404a05, ee70ecc, e404a05
