### ISSUE TITLE
Boost links against wrong python library version

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#50]
This has started happening as of #42 
It looks like [a bug in the CMake Boost discovery script](https://stackoverflow.com/a/50464498), which can be resolved by [appending the appropriate Python version number to the Boost component dependencies](https://github.com/Kitware/CMake/commit/c747d4ccb349f87963a8d1da69394bc4db6b74ed).

This has been fixed in a relatively recent version of [CMake, which is not yet available via APT](https://packages.ubuntu.com/xenial/cmake).
This is not a GIFT-Grab problem, however opening this ticket for the record.

**Comment by dzhoshkun** [comment]
[CMake version 3.8.2 seems to be the first release after the above fix](https://github.com/Kitware/CMake/releases/tag/v3.8.2)

**Comment by dzhoshkun** [comment]
* [ ] why are both `libboost_python` versions are linked in the above failing build?

```bash
gitlab-runner@gift-adelie:~/giftgrab-scratch/1af4b6b/build/py35$ ldd pygiftgrab.so 
	libboost_python3.so.1.63.0 => /home/gitlab-runner/environments/giftgrab/install/boost/lib/libboost_python3.so.1.63.0 (0x00007fd315ff8000)
	libboost_numpy3.so.1.63.0 => /home/gitlab-runner/environments/giftgrab/install/boost/lib/libboost_numpy3.so.1.63.0 (0x00007fd315dec000)
	libgiftgrab.so => /home/gitlab-runner/giftgrab-scratch/1af4b6b/build/py35/libgiftgrab.so (0x00007fd315bc7000)
	libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007fd313d92000)
        ...
	libboost_python.so.1.63.0 => /usr/local/lib/libboost_python.so.1.63.0 (0x00007fd312fc5000)
```

**Comment by dzhoshkun** [comment]
The problem seems to be related to the `gitlab-runner` user, while for `dzhoshkun`:

```bash
[0] % ldd pygiftgrab.so 
	libboost_python3.so.1.63.0 => /home/dzhoshkun/ws/_i/boost/lib/libboost_python3.so.1.63.0 (0x00007f91a6667000)
	libboost_numpy3.so.1.63.0 => /home/dzhoshkun/ws/_i/boost/lib/libboost_numpy3.so.1.63.0 (0x00007f91a645b000)
	libgiftgrab.so => /home/dzhoshkun/ws/giftgrab-scratch/4ed116a/build/py35/libgiftgrab.so (0x00007f91a6236000)
	libpython3.5m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0 (0x00007f91a4434000)
	...
	libboost_python.so.1.63.0 => /home/dzhoshkun/ws/_i/boost/lib/libboost_python.so.1.63.0 (0x00007f91a3667000)
```

**Comment by dzhoshkun** [comment]
Looks like https://github.com/gift-surg/GIFT-Grab/issues/50#issuecomment-437319045 is related to the activation of FFmpeg in CMake configuration.
In particular, FFmpeg is discovered using pkg-config, which adds compiler and linker flags to the configuration (e.g. `pkg-config --libs --cflags libavcodec` produces `-I/usr/local/include -L/usr/local/lib -lavcodec`.
Possibly `-L/usr/local/lib` confuses the linker about `libboost_python.so`, which is **not** explicitly requested, but somehow finds its way into the scene.

**Comment by joubs** [comment]
Closing as out of date.
