### ISSUE TITLE
Infinite loop in FFmpeg video source frame decoding

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#51]
It looks like some video files lead to infinite loops in the [FFmpeg decoding code of GIFT-Grab](https://github.com/gift-surg/GIFT-Grab/blob/468473f6b81735190653f25b63e64d0f875ff944/src/ffmpeg/ffmpeg_video_source.cpp#L105).
There is a [pointer to an "infinite loop" in the FFmpeg decoding example](https://github.com/FFmpeg/FFmpeg/blob/903f2beafc7c5379ff65a7ca9b9e7b7ee49c75bf/libavcodec/decode.c#L586).
But we need to investigate this a bit more deeply to fix the problem.

**Comment by joubs** [comment]
Closing as out of date.
