### ISSUE TITLE
CodeDocs should show only public API

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#52]
Right now documentation is shown for all visibility levels.
This is a bit confusing.
See for instance the [`VideoFrame` class](https://codedocs.xyz/gift-surg/GIFT-Grab/classgg_1_1_video_frame.html).
Apparently this involves [reconfiguration of doxygen](https://stackoverflow.com/a/11316802), but it might be possible to set it on CodeDocs as well.
The latter option is more straightforward, if available.

**Comment by joubs** [comment]
Closing as out of date.
