### ISSUE TITLE
mac support?

### ISSUE THREAD

**Issue by pasha76** [gift-surg/GIFT-Grab#54]
Hello, can I install grift-grab on Mac machine?

**Comment by dzhoshkun** [comment]
Hi @pasha76 Thanks for your interest. We have tested GIFT-Grab on Linux so far. However Mac OS is a UNIX-like system, and GIFT-Grab uses cross-platform tools for discovering its dependencies. So you should be able to install it on a Mac.

What [feature of GIFT-Grab](https://github.com/gift-surg/GIFT-Grab#features) are you interested in?

**Comment by joubs** [comment]
Closing as out of date.
