### ISSUE TITLE
Encoding stereo streams

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#57]
How are stereo frames encoded by modern tools such as FFmpeg?
The answer to this question might help guide the design of #18

**Comment by tvercaut** [comment]
Out of curiosity, I googled a bit. Some interesting links I cam across:
- https://en.wikipedia.org/wiki/Comparison_of_video_container_formats (note the 3D codec column)
- https://www.matroska.org/technical/specs/notes.html#3D
- https://www.ffmpeg.org/doxygen/trunk/group__lavu__video__stereo3d.html
- https://ffmpeg.org/ffmpeg-filters.html#stereo3d
- https://headjack.io/blog/best-encoding-settings-resolution-for-4k-360-3d-vr-videos/
- https://www.webmproject.org/docs/container/#StereoMode

**Comment by dzhoshkun** [comment]
Thanks @tvercaut These look useful.

**Comment by dzhoshkun** [comment]
Our current layout is the `AV_STEREO3D_TOPBOTTOM` layout of the third link in https://github.com/gift-surg/GIFT-Grab/issues/57#issuecomment-438671646

**Comment by tvercaut** [comment]
Further information on this. HEVC also has a more generic multi-view extension that might be interesting but is probably not yet very mature:
- https://hevc.hhi.fraunhofer.de/mvhevc
- https://hevc.hhi.fraunhofer.de/trac/3d-hevc/browser/3DVCSoftware/trunk (BSD license reference implementation)
- https://en.wikipedia.org/wiki/Multiview_Video_Coding

**Comment by joubs** [comment]
Closing as out of date.
