### ISSUE TITLE
Use SDK-specific pixel format in constructors

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#59]
For instance as part of #30 12-bit RGB to BGRA conversion is being implemented.
This is to be able to support BGRA captures using DeckLink 4K Extreme 12G devices.
Blackmagic cards have well-defined pixel formats that are supported at the capture level, however in the current architecture after #30, all BM cards will be forced to use 12-bit RGB as the capture format.
This might cause problems, for instance with other cards in the future that support only other RGB-class pixel formats.
The solution to this is probably to:

* [ ] use the SDK-specific pixel formats in video source constructors
* [ ] and determine those based on the `Device` passed to the video source factory's method

**Comment by joubs** [comment]
Closing as out of date.
