### ISSUE TITLE
Transition from GitHub-as-CMICLab-mirror to GitHub-as-main-repo

### ISSUE THREAD

**Issue by tvercaut** [gift-surg/GIFT-Grab#6]
A number of issues are being worked from https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab

To better support GIFT-Grab going forward we should deprecate the use the CMICLab as the main repository for this project.

**Comment by dzhoshkun** [comment]
* [x] Depends on #7

**Comment by dzhoshkun** [comment]
The CmicLab project has also been [archived](https://docs.gitlab.com/ce/user/project/settings/#archiving-a-project) now.

**Comment by dzhoshkun** [comment]
* [x] depends on #8

**Comment by dzhoshkun** [comment]
* [x] also remove the mirroring hook on CMICLab

**Comment by dzhoshkun** [comment]
For the record, the `post-receive` hook on cmiclab was moved to `~git/backups/`

**Comment by dzhoshkun** [comment]
Currently there is an issue branch only for #3 [on CMICLab](https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/merge_requests/53). That branch is now transferred to GitHub as well.

**Comment by dzhoshkun** [comment]
* [x] sift the [open issue tickets on CMICLab](https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues)

**Comment by dzhoshkun** [comment]
* [ ] Open issues on CMICLab worth keeping:
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/233
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/232
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/209 🥇 
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/200
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/196
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/193
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/189
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/184
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/182
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/181
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/173
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/167 🥇 
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/166
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/165 (can this be combined with [TBB](https://www.threadingbuildingblocks.org/), just [as it's done in supra](https://doi.org/10.1007/s11548-018-1750-6)?)
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/160
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/155
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/147 (device-independent, fast alternative?), related issue:
   * https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/136
   * an alternative might be to provide a `NotImplementedException`
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/140
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/138 (good for synchronisation)
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/130
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/124
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/97
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/96
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/95
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/80
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/58
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/54
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/50 🥇 
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/49 🥇 
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/38 🥇 
* https://cmiclab.cs.ucl.ac.uk/GIFT-Surg/GIFT-Grab/issues/17 🥇 (idea only)

**Comment by joubs** [comment]
Closing as out of date

**Comment by tvercaut** [comment]
[gift-surg-gift-grab_issues_2020-12-02.csv.zip](https://github.com/gift-surg/GIFT-Grab/files/5628768/gift-surg-gift-grab_issues_2020-12-02.csv.zip)
