### ISSUE TITLE
Does DeckLink 4K Extreme 12G support BGRA captures?

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#60]
As of #30, it doesn't appear to support the attempted 12-bit RGB, BGRA, or ARGB.
It'd be good to clarify this with the support team.

Relevant info: https://forum.blackmagicdesign.com/viewtopic.php?f=12&t=69361&p=387723&hilit=bgra#p387723

**Comment by joubs** [comment]
Closing as out of date
