### ISSUE TITLE
Support (or documentation) for (near-)lossless encoding

### ISSUE THREAD

**Issue by tvercaut** [gift-surg/GIFT-Grab#64]
For many research project, having an easy to configure (near-)lossless compression mode would be good. Tradeoff to consider:
- Final file size
- Encoding speed
- Indeed qualifying as (near-)lossless

Some interesting pointers:
- nvenc supports lossless https://developer.nvidia.com/nvidia-video-codec-sdk
- kvazaar support lossless hevc https://github.com/ultravideo/kvazaar#parameters
- https://trac.ffmpeg.org/wiki/Encode/VP9#LosslessVP9
- https://trac.ffmpeg.org/wiki/Encode/H.264#LosslessH.264
- Maybe look into ProRes http://forum.doom9.org/archive/index.php/t-174236.html
- https://x265.readthedocs.io/en/default/lossless.html

**Comment by joubs** [comment]
Closing as out of date.
