### ISSUE TITLE
PythonLibs version check in Boost.Python discovery messes up PyPI installation

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#83]
Related to #69 (in particular #81). The [Linux CI script](https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/193177949) succeeds, while the [PyPI one](https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/193177952) fails. This is because the [Boost.Python check step of the pip installer](https://github.com/gift-surg/GIFT-Grab/blob/c5481aa22e5a5f1a68dd3453040b3df01c6c8208/src/setup.py#L264) is run separately from the PythonLibs check (see section directly above), whereby no [`PYTHONLIBS_VERSION_STRING`](https://cmake.org/cmake/help/v3.2/module/FindPythonLibs.html) is being cached.

**Comment by joubs** [comment]
Closing as out of date.
