### ISSUE TITLE
Generate import library on Windows builds

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#84]
This is for #69 In particular within #78 it's been discovered that an import library is not being generated, as GG does not have [the relevant directives](https://stackoverflow.com/a/33297026) in place. These directives should be added to the public API elements. A yard stick for quickly testing this is to link an executable with GIFT-Grab DLL on Windows.

**Comment by joubs** [comment]
Closing as out of date.
