### ISSUE TITLE
Experimental Windows support branch

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#91]
A lot of the work needed for supporting GIFT-Grab (in particular Epiphan DVI2PCIe Duo) has been done as part of #69. However the PRs have been polluted, as a number of compilation issues have had to be fixed on the fly.

Many of those changes can be used when supporting Windows officially in the (hopefully near) future. So possibly a good way forward is to have an experimental Windows support branch (that can be advertised on the documentation). We can cherry-pick changes from the #69 branch, and merge them onto this branch, in well-defined PRs that clearly show the changes. This will allow to document remaining issues, which can then be addressed in an orderly way to pave the way to official Windows support.

**Comment by dzhoshkun** [comment]
This has already been achieved, see https://github.com/gift-surg/GIFT-Grab/tree/experimental-windows But will leave it open to facilitate thought on how this can be managed w.r.t. the stable branch.

**Comment by joubs** [comment]
Closing as out of date
